SET(HIK_APP_COMPONENTS_ROOT $ENV{HPT_REPOSITORY}/$ENV{HPT_PLATFORM}/$ENV{HPT_CHANNEL}/$ENV{HPT_DEP_PROJECT})
IF (EXISTS ${HIK_APP_COMPONENTS_ROOT})
    MESSAGE(STATUS "${BN}$ENV{HPT_DEP_PROJECT} 依赖路径: ${HIK_APP_COMPONENTS_ROOT} 有效${OO}")
ELSE ()
    MESSAGE(WARNING "需要配置一个这样的路径 ${DS}{HPT_REPOSITORY}/win64/release/hik.app")
    MESSAGE(FATAL_ERROR "${BR}$ENV{HPT_DEP_PROJECT} 依赖路径: ${HIK_APP_COMPONENTS_ROOT} 不存在${OO}")
ENDIF ()

SET(REQUIRED_COMPONENTS
        "BasicTypes/V1.1.0"
)

FOREACH (COMPONENT ${REQUIRED_COMPONENTS})
    SET(HIK_DEP_DIR ${HIK_APP_COMPONENTS_ROOT}/${COMPONENT})
    IF (EXISTS ${HIK_DEP_DIR})
        MESSAGE(STATUS "${BB}添加依赖并复制.dll: ${COMPONENT}${OO}")
        INCLUDE_DIRECTORIES(${HIK_DEP_DIR}/include)
        LINK_DIRECTORIES(${HIK_DEP_DIR}/bin)
        FILE(GLOB HIK_APP_DLL_FILES "${HIK_DEP_DIR}/bin/*.dll")
        # FILE(COPY ${HIK_APP_DLL_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX})
        # MESSAGE(STATUS "FILE(COPY ${HIK_APP_DLL_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX})")
        # LIST(APPEND HIK_APP_DLL_FILES ${TEMP_DLL_FILES}) # 也可以先暂存起来在最后才copy
    ELSE ()
        MESSAGE(STATUS "${BR}组件未在 ${HIK_APP_COMPONENTS_ROOT} 中找到: ${COMPONENT}${OO}")
    ENDIF ()
ENDFOREACH ()
