ADD_CUSTOM_COMMAND(TARGET ${BIN_TARGET} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}
        COMMAND ${CMAKE_COMMAND} -E copy_directory
        "${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}"
        "${CMAKE_INSTALL_PREFIX}/"
        COMMENT "复制成果物到 ${CMAKE_INSTALL_PREFIX}/"
)
